In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('Countries.csv')

In [8]:
# which countri has the highest population
df[df['population']==df['population'].max()]['country']

75    India
Name: country, dtype: object

In [11]:
# what is the capital of  country with highest population

# what is the capital of  country with highest population
# df.loc[df['population'].idxmax(),'capital_city']

df[df['population']==df['population'].max()][['capital_city','country']]

   capital_city country
75    New Delhi   India

In [12]:
# what is the capital of  country with least population

df[df['population']==df['population'].min()][['capital_city','country']]

    capital_city country
179     Funafuti  Tuvalu

In [87]:
# what is the capital of  country with least population
# df.loc[df['population'].idxmin(),'capital_city']     #for kown df.sort_values(by='population', ascending=True).head()

    capital_city country
179     Funafuti  Tuvalu

In [18]:
# give me top 5 countries with highest democratic score   for want to knowdf.sort_values(by='democracy_score',ascending=False)
df.sort_values(by='democracy_score',ascending=False).head(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [22]:
# how many total regions are there
df['region'].unique()

array(['Southern Asia', 'Southern Europe', 'Northern Africa',
       'Middle Africa', 'Caribbean', 'South America', 'Western Asia',
       'Australia and New Zealand', 'Western Europe', 'Eastern Europe',
       'Central America', 'Western Africa', 'Southern Africa',
       'South-Eastern Asia', 'Eastern Africa', 'Northern America',
       'Eastern Asia', 'Northern Europe', 'Melanesia', 'Central Asia',
       'Micronesia', 'Polynesia'], dtype=object)

In [19]:
df['region'].value_counts().count()

np.int64(22)

In [5]:
# how many countries lie in Estern Europe region
# df.loc[df['region']=='Eastern Europe','country'] #konsi

df['region'].value_counts()[['Eastern Europe']]

np.int64(10)

region
Eastern Europe    10
Name: count, dtype: int64

In [54]:
# who is the political leader of the first highest poluted country
df[df['population']==df['population'].max()][['political_leader','country']]

   political_leader country
75    Narendra Modi   India

In [61]:
df.sort_values(by='population',ascending=False).iloc[1][['political_leader','country']]

political_leader    Xi Jinping
country                  China
Name: 34, dtype: object

In [7]:
# how many countries are there who's leaders are unknown
df[df['political_leader'].isna()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.8889,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.500000,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
159,St. Kitts and Nevis,St. Kitts and Nevis,East Caribbean dollar,Basseterre,Caribbean,Americas,Kittian and Nevisian,17.333333,-62.750000,60.0,...,47657,31.2500,32888,14769,0.00,0.00,Unknown,30.4,NaN,NaN
160,St. Lucia,St. Lucia,East Caribbean dollar,Castries,Caribbean,Americas,Saint Lucian,13.883333,-60.966667,99.4,...,179857,11.1111,145594,34263,0.00,0.00,Unknown,29.5,NaN,NaN
161,St. Vincent and the Grenadines,St. Vincent and the Grenadines,East Caribbean dollar,Kingstown,Caribbean,Americas,Saint Vincentian,13.250000,-61.200000,70.0,...,103948,18.1818,47946,56002,0.00,0.00,Unknown,29.1,NaN,NaN
172,Timor-Leste,Democratic Republic of Timor-Leste,U.S. dollar,Dili,South-Eastern Asia,Asia,East Timorese,-8.833333,125.916667,3414.0,...,1341296,40.0000,911089,430207,2.61,7.19,Flawed democracy,16.7,NaN,NaN
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN

In [75]:
# how many country have their republic in fullform
df[df['country']==df['country_long']]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.050000,-61.800000,90.0,...,93763,11.11110,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
13,Barbados,Barbados,Barbados dollar,Bridgetown,Caribbean,Americas,Barbadian,13.166667,-59.533333,100.0,...,281635,26.66670,193416,88219,0.00,0.00,Unknown,35.2,Mia Mottley,Prime Minister
16,Belize,Belize,Belize dollar,Belmopan,Central America,Americas,Belizean,17.250000,-88.750000,1720.0,...,405272,12.50000,217242,188030,2.84,0.00,Unknown,21.6,Dean Barrow,Prime Minister
20,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina convertible mark,Sarajevo,Southern Europe,Europe,Bosnian,44.000000,18.000000,22160.0,...,3233526,16.66670,1621904,1611622,2.69,4.98,Hybrid regime,38.1,Valentin Inzko,High Representative
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
30,Canada,Canada,Canadian dollar,Ottawa,Northern America,Americas,Canadian,60.000000,-95.000000,577430.0,...,38929902,30.47340,7103929,31825973,4.98,9.15,Full democracy,36.4,Justin Trudeau,Prime Minister
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.0,...,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President
43,Czech Republic,Czech Republic,Czech koruna,Prague,Eastern Europe,Europe,Czech,49.750000,15.500000,35238.7,...,10526073,25.50000,2697096,7828977,3.14,7.69,Flawed democracy,38.8,Andrej Babiš,Prime Minister
49,Dominican Republic,Dominican Republic,Dominican peso,Santo Domingo,Caribbean,Americas,Dominican,19.000000,-70.666667,24290.0,...,11228821,27.89470,1813679,9415142,2.80,6.54,Flawed democracy,23.4,Danilo Medina,President
62,Georgia,Georgia,Georgian lari,Tbilisi,Western Asia,Asia,Georgian,42.000000,43.500000,23779.0,...,3712502,19.04760,1473975,2238527,2.70,5.50,Hybrid regime,32.5,Giorgi Gakharia,Prime Minister
66,Grenada,Grenada,East Caribbean dollar,St. George's,Caribbean,Americas,Grenadian,12.116667,-61.666667,80.0,...,125438,31.25000,79192,46246,0.00,0.00,Unknown,27.1,Keith Mitchell,Prime Minister
73,Hungary,Hungary,Hungarian forint,Budapest,Eastern Europe,Europe,Hungarian,47.000000,20.000000,49030.0,...,9683505,14.07040,2657928,7025577,2.57,6.63,Flawed democracy,38.1,Viktor Orbán,Prime Minister
79,Ireland,Ireland,Euro,Dublin,Northern Europe,Europe,Irish,53.000000,-8.000000,45120.0,...,5086988,23.12500,1822006,3264982,5.21,9.15,Full democracy,33.9,Leo Varadkar,Taoiseach
82,Jamaica,Jamaica,Jamaican dollar,Kingston,Caribbean,Americas,Jamaican,18.250000,-77.500000,4440.0,...,2827377,28.57140,1215546,1611831,7.03,7.02,Flawed democracy,27.3,Andrew Holness,Prime Minister
83,Japan,Japan,Japanese yen,Tokyo,Eastern Asia,Asia,Japanese,36.000000,138.000000,43720.0,...,125124989,9.91379,10066305,115058684,2.66,7.99,Flawed democracy,44.7,Yoshihide Suga,Prime Minister
90,Kyrgyz Republic,Kyrgyz Republic,Kyrgyz som,Bishkek,Central Asia,Asia,Kirghiz,41.000000,75.000000,103678.0,...,6803300,20.45450,4254716,2548584,2.61,5.11,Hybrid regime,19.8,Mukhammedkalyi Abylgaziev,Prime Minister
102,Malaysia,Malaysia,Malaysian ringgit,Kuala Lumpur,South-Eastern Asia,Asia,Malaysian,2.500000,112.500000,85710.0,...,33938221,13.57470,7393781,26544440,2.13,6.88,Flawed democracy,26.3,Muhyiddin Yassin,Prime Minister
113,Mongolia,Mongolia,Mongolian tugrik,Ulan Bator,Eastern Asia,Asia,Mongolian,46.000000,105.000000,1127000.0,...,3398366,17.10530,1055872,2342494,2.65,6.50,Flawed democracy,22.9,Khaltmaagiin Battulga,President
114,Montenegro,Montenegro,Euro,Podgorica,Southern Europe,Europe,Montenegrin,42.500000,19.300000,2579.5,...,616159,27.16050,196160,419999,2.39,5.74,Hybrid regime,34.4,Duško Marković,Prime Minister
120,Nepal,Nepal,Nepalese rupee,Kathmandu,Southern Asia,Asia,Nepalese,28.000000,84.000000,41210.0,...,30547580,33.09090,23994819,6552761,2.34,5.18,Hybrid regime,20.0,KP Sharma Oli,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.000000,174.000000,101540.0,...,5124100,50.42020,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
139,Romania,Romania,New Romanian leu,Bucharest,Eastern Europe,Europe,Romanian,46.000000,25.000000,135910.0,...,18956666,19.09090,8627368,10329298,3.05,6.38,Flawed democracy,37.4,Klaus Iohannis,President
142,Samoa,Samoa,Samoan tala,Apia,Polynesia,Oceania,Samoan,-13.583333,-172.333333,494.1,...,222382,12.96300,183207,39175,4.28,0.00,Unknown,16.7,Tuilaepa Aiono Sailele Malielegaoi,Prime Minister
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.500000,18830.0,...,5431752,21.33330,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
153,Solomon Islands,Solomon Islands,Solomon Islands dollar,Honiara,Melanesia,Oceania,Solomon Islander,-8.000000,159.000000,1170.0,...,724273,8.00000,538975,185298,0.00,0.00,Unknown,15.4,Manasseh Sogavare,Prime Minister
159,St. Kitts and Nevis,St. Kitts and Nevis,East Caribbean dollar,Basseterre,Caribbean,Americas,Kittian and Nevisian,17.333333,-62.750000,60.0,...,47657,31.25000,32888,14769,0.00,0.00,Unknown,30.4,NaN,NaN
160,St. Lucia,St. Lucia,East Caribbean dollar,Castries,Caribbean,Americas,Saint Lucian,13.883333,-60.966667,99.4,...,179857,11.11110,145594,34263,0.00,0.00,Unknown,29.5,NaN,NaN
161,St. Vincent and the Grenadines,St. Vincent and the Grenadines,East Caribbean dollar,Kingstown,Caribbean,Americas,Saint Vincentian,13.250000,-61.200000,70.0,...,103948,18.18180,47946,56002,0.00,0.00,Unknown,29.1,NaN,NaN
165,Switzerland,Switzerland,Swiss franc,Bern,Western Europe,Europe,Swiss,47.000000,8.000000,15042.1,...,8769741,41.50000,2272064,6497677,7.43,9.03,Full democracy,38.1,Simonetta Sommaruga,President
166,Syrian Arab Republic,Syrian Arab Republic,Syrian pound,Damascus,Western Asia,Asia,Syrian,35.000000,38.000000,139210.0,...,22125249,11.20000,9564966,12560283,1.09,1.43,Authoritarian,17.7,Bashar al-Assad,President
178,Turkmenistan,Turkmenistan,New Turkmen manat,Ashgabat,Central Asia,Asia,Turkmen,40.000000,60.000000,338380.0,...,6430770,25.86210,2990694,3440076,0.92,1.72,Authoritarian,22.0,Gurbanguly Berdimuhamedow,President
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.000000,178.000000,18.0,...,11312,6.25000,3900,7412,0.00,0.00,Unknown,21.0,Kausea Natano,Prime Minister
181,Ukraine,Ukraine,Ukrainian hryvnia,Kiev,Eastern Europe,Europe,Ukrainian,49.000000,32.000000,413110.0,...,38000000,20.33100,11430780,26569220,2.41,5.69,Hybrid regime,38.9,Volodymyr Zelensky,President
182,United Arab Emirates,United Arab Emirates,U.A.E. dirham,Abu Dhabi,Western Asia,Asia,Emirati,24.000000,54.000000,3898.0,...,9441129,50.00000,1176081,8265048,1.79,2.76,Authoritarian,29.3,Sheikh Khalifa bin Zayed Al Nahyan,President
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN

In [10]:
# how many country have their republic in fullform
df['country_long'].str.lower().str.contains('republic').sum()

np.int64(125)

In [16]:
# which country in african region has the highest population

# African countries
afdf = df[df['region'].str.contains('Africa')]

# Country with highest population in Africa
afdf[afdf['population'] == afdf['population'].max()][['country', 'population']]

     country  population
125  Nigeria   218541212